### ISSUE TITLE
What about having OrangeClock on Orange Pi instead of Raspberry Pi?

### ISSUE THREAD

**Issue by smartm0use** [marc3linho/OrangeClock#21]
Isn't mine a legit question? :D

**Comment by marc3linho** [comment]
Sorry for the late reply.I did not know the OrangePI ecosystem until now.

**Comment by marc3linho** [comment]
I will close this issue because I could not find a version like the pico from orange pi

**Comment by marc3linho** [comment]
I will close this issue because I could not find a version like the pico from orange pi

**Comment by marc3linho** [comment]
I will close this issue because I could not find a version like the pico from orange pi
