### ISSUE TITLE
Cannot get back to setup after incorrect SSID input(user error!)

### ISSUE THREAD

**Issue by osilloh** [marc3linho/OrangeClock#42]
**Describe the bug**
After entering an incorrect SSID/password combination I have been unable to get back to the setup via browing to orange.clock or direct IP 192.168.4.1

**To Reproduce**
Enter incorrect SSID/password? 

This is what I see in Thonny shell/console

Entering setup mode...
sync full refresh
show time 175 ms
wait_until_ready 5103ms   0.1mins
wait_until_ready 0ms   0.0mins
sync full refresh
show time 175 ms
wait_until_ready 5103ms   0.1mins
wait_until_ready 0ms   0.0mins
sleep
sleep
2023-12-24 08:14:49 [info     /  87kB] > starting catch all dns server on port 53
2023-12-24 08:14:49 [info     /  85kB] > starting web server on port 80
2023-12-24 08:17:51 [info     / 100kB] > GET /favicon.ico (404 Not Found) [304ms]
2023-12-24 08:21:52 [debug    /  85kB] > parsed template: ap_templates/redirect.html (took 10 ms)
2023-12-24 08:21:52 [info     /  83kB] > GET / (200 OK) [160ms]
2023-12-24 08:21:52 [debug    /  74kB] > parsed template: ap_templates/redirect.html (took 11 ms)
2023-12-24 08:21:52 [info     /  71kB] > GET /favicon.ico (200 OK) [149ms]

**Expected behavior**
prompt on browser to configure SSID and password again.

**Screenshots**

**Additional context**
I see this code in Thonny, but it does not appear to be getting to this as I do not see any update on the pi screen, or in Thonny shell/console. I also tried deleting all files on the Pi and uploading them again. I suppose there is some kind of hidden setup file that I didn't delete?

# Figure out which mode to start up in...
try:
    os.stat(WIFI_FILE)

    # File was found, attempt to connect to wifi...
    with open(WIFI_FILE) as f:
        wifi_credentials = json.load(f)
        ip_address = connect_to_wifi(wifi_credentials["ssid"], wifi_credentials["password"])

        if not is_connected_to_wifi():
            # Bad configuration, delete the credentials file, reboot
            # into setup mode to get new credentials from the user.
            print("Bad wifi connection!")
            print(wifi_credentials)
            os.remove(WIFI_FILE)
            machine_reset()

        print(f"Connected to wifi, IP address {ip_address}")
        application_mode()

**Comment by osilloh** [comment]
Interestingly after several hours, my browser came up to the setup screen on orange.clock and I was able to complete the config properly. :)

**Comment by osilloh** [comment]
Interestingly after several hours, my browser came up to the setup screen on orange.clock and I was able to complete the config properly. :)

**Comment by marc3linho** [comment]
Thank you for sharing this unexpected behavior
