### ISSUE TITLE
Unable to detect WIFI 

### ISSUE THREAD

**Issue by BitcoinBastiat** [marc3linho/OrangeClock#47]
Cant find the orange clock SSID. I copied over all the python script files (one at a time) because I was not able to select all of the SRC file at once. This led to the HTML files not being able to be copied over into thonny. I'm new to python running thonny on macbook. I am able to test the LED on the Pico so I know that the python commands are working at least.

**Comment by marc3linho** [comment]
Hi @BitcoinBastiat , I think the way of copying is the problem.

It is necessary to bring the folder structure onto the Pico as shown in the image below. With the exception of wifi.json which is created automatically after setup
https://raw.githubusercontent.com/marc3linho/OrangeClock/main/images/readme/thonny_1.png

It should also be possible to copy all files in Thonny at once under Mac

**Comment by BitcoinBastiat** [comment]
OK. I will try again. I wasn't able to just drag and drop unfortunately. I'll have to try again and see if I'm missing something. Is there any sort of special considerations with the Pico/thonny to just delete the OS and start over?

**Comment by jdlcdl** [comment]
> Is there any sort of special considerations with the Pico/thonny to just delete the OS and start over?

Do you know of the "flash_nuke.uf2" method?

It's the same process as dropping a new micropython-for-pico firmware onto the pico... you have to press the "boot select" button while powering it on, then you drop a firmware file, in this case it's `flash_nuke.uf2` onto the new usb-drive "RPI-RP2" which represents your pico.

I've played with this extensively.  As far as I can tell, your entire flash will be erased and you'll then be starting with a virgin device.

Here are the [docs](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html#resetting-flash-memory)
